name: Build APK

on:
  push:
    branches: [main]
    paths-ignore:
    - README.md
    - docs/**
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      EXPO_PUBLIC_APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
      EXPO_PUBLIC_APPWRITE_PROJECT_NAME: ${{ secrets.APPWRITE_PROJECT_NAME }}
      EXPO_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
      EXPO_PUBLIC_BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Expo prebuild
        run: npx expo prebuild

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
